# Generated by Django 5.1.3 on 2024-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_booth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
