# Generated by Django 5.1.3 on 2024-11-14 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_admission_date_customuser_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='certificates',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('booth_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('past_participants', models.ManyToManyField(blank=True, related_name='participated_booths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoothQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.booth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('booth', 'user')},
            },
        ),
        migrations.AddField(
            model_name='booth',
            name='queue',
            field=models.ManyToManyField(blank=True, related_name='waiting_booths', through='users.BoothQueue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=50, unique=True)),
                ('promotional_content', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('applicants', models.ManyToManyField(blank=True, related_name='interested_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='users.company'),
        ),
    ]
