# Generated by Django 5.1.3 on 2024-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='boothCate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='boothName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='boothNum',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booth',
            name='floor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
