# Generated by Django 5.1.3 on 2024-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_booth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='day',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='booth',
            name='floor',
            field=models.CharField(default=0),
        ),
    ]
