# Generated by Django 5.1.3 on 2024-11-14 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booth_current_consultation_booth_wait_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='queue',
        ),
        migrations.AddField(
            model_name='booth',
            name='queue',
            field=models.ManyToManyField(blank=True, related_name='booth_queue', to=settings.AUTH_USER_MODEL),
        ),
    ]
