# Generated by Django 5.1.3 on 2024-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
