# Generated by Django 5.1.3 on 2024-11-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_booth_queue_booth_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
