# Generated by Django 5.1.3 on 2024-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reservation_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
