# Generated by Django 5.1.3 on 2024-11-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_manager'),
        ('users', '0009_interestcategory_customuser_interest_categories'),
    ]

    operations = [
    ]
