# Generated by Django 5.1.3 on 2024-11-14 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20241114_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='past_participants',
        ),
    ]
