# Generated by Django 5.1.3 on 2024-11-14 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_booth_past_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='completed_consultations',
            field=models.ManyToManyField(blank=True, related_name='consulted_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
